call plug#begin()

" List your plugins here
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
let g:airline_theme='badwolf'
let g:airline_powerline_fonts = 1

Plug 'Valloric/YouCompleteMe'

call plug#end()
