call plug#begin()

" List your plugins here
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme='ayu_mirage'
let g:airline_powerline_fonts = 1

Plug 'Valloric/YouCompleteMe'

call plug#end()
